### ISSUE TITLE
Any solution to upload the scritp (host cpanel)?

### ISSUE THREAD

**Issue by maximoxr** [ltt2801/new-vinaget-script#16]
When trying to upload the script to hosting, cpanel detects it as a virus, by ftp it is uploaded and after a few seconds it is removed by the cpanel antivirus.

Attached screenshot

![vinaerror](https://user-images.githubusercontent.com/52300844/60307169-10f8b180-9909-11e9-9bf2-7cde4f995d1a.jpg)

**Comment by ltt2801** [comment]
Your Cpanel does not support to use Vinaget. You should change other hosting provider.
