### ISSUE TITLE
add plugins streaming video

### ISSUE THREAD

**Issue by totaldebrid** [ltt2801/new-vinaget-script#17]
hi is possible to add plugins streaming video
openload.co, streamango.com, verystream.com, userscloud.com, uqpload.com, upvid.co, gounlimited.to and more
please thank you possible to pay and plugins contact me to referencemega@gmail.com

**Comment by ltt2801** [comment]
We need a streaming link for this issue. Truely, after you generate the download link, you can include some video streaming scripts like videojs, plyr, elementmedia, etc.

**Comment by totaldebrid** [comment]
to link and video streaming 

https://openload.co/embed/OnwRTc26tGw
https://streamango.com/embed/rbddkatndeomntca
https://verystream.com/e/ebsgbGWrh55/
https://userscloud.com/ywp6fws6idnm
https://gounlimited.to/embed-romjxl9wegw3.html
and more
