### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by fafaka** [ltt2801/new-vinaget-script#2]
after i finish installing it shows "HTTP ERROR 500".

my vps system is Centos 6 in 64 bits.

**Comment by ltt2801** [comment]
Please open port 80 to use, change AllowOverride All in httpd.conf then service httpd restart

**Comment by fafaka** [comment]
thx and it works!

**Comment by fafaka** [comment]
Thx and it’s OK now.

Btw, can you make plugin for uploadgig.com and upstore.net these 2 sites?

Regards
fafaka

发件人: Thanh Tuấn<mailto:notifications@github.com>
发送时间: 2017年9月10日 23:19
收件人: ltt2801/new-vinaget-script<mailto:new-vinaget-script@noreply.github.com>
抄送: fafaka<mailto:getnbagames@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [ltt2801/new-vinaget-script] HTTP ERROR 500 (#2)


Please open port 80 to use, change AllowOverride All in httpd.conf then service httpd restart
